import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/frame">Frame</Link>
        </li>
        <li>
          <Link to="/frame1">Frame1</Link>
        </li>
        <li>
          <Link to="/frametwo">FrameTwo</Link>
        </li>
        <li>
          <Link to="/frame2">Frame2</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
